### ISSUE TITLE
Add automated maintenance workflows

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/requests-magpie#7]
I realize that this project is very minimal, but here's what I'd like to add:
- Dependabot
- Trusted Publishing

@fmigneault Think you could add me to the PyPI maintainers?
@davidcaron Hey, if you're still around, think you could add Francis and me to the TestPyPI owners?

Cheers,

**Comment by fmigneault** [comment]
@Zeitsperre done

**Comment by Zeitsperre** [comment]
Thanks, @fmigneault! I realize that in order to add trusted publishing, we need an owner to set that up. If you could do the following, that will be the end of things needed:

- Go to Projects → Manage → Publishing
- Add a new publisher:
  - Owner: Ouranosinc
  - Repository name: requests-magpie
  - Workflow name: publish-pypi.yml
  - Environment name: production

**Comment by Zeitsperre** [comment]
Closed with #12
